### ISSUE TITLE
Cannot install on Visual Studio 2013

### ISSUE THREAD

**Issue by varnk** [mirik123/tfsprod#1]
I have both Visual Studio 2010 and Visual Studio 2013 installed.  When I try to run the installer I get this in the error log and the install fails:

1/12/2016 9:52:08 AM - Microsoft VSIX Installer
1/12/2016 9:52:08 AM - -------------------------------------------
1/12/2016 9:52:08 AM - Initializing Install...
1/12/2016 9:52:08 AM - Extension Details...
1/12/2016 9:52:08 AM - 	Identifier      : 16bf0a1d-6239-485f-ac25-6fcd37d514c7
1/12/2016 9:52:08 AM - 	Name            : TFS Productivity Tools
1/12/2016 9:52:08 AM - 	Author          : Mark Babayev
1/12/2016 9:52:08 AM - 	Version         : 2.1.0
1/12/2016 9:52:08 AM - 	Description     : The TFS Productivity Tools project was designed to provide TFS administrators with helper extensions for Source Control or Work Item Tracking tasks.
1/12/2016 9:52:08 AM - 	Locale          : en-US
1/12/2016 9:52:08 AM - 	MoreInfoURL     : https://github.com/mirik123/tfsprod
1/12/2016 9:52:08 AM - 	InstalledByMSI  : False
1/12/2016 9:52:08 AM - 	SupportedFrameworkVersionRange : [4.5]
1/12/2016 9:52:08 AM - 
1/12/2016 9:52:08 AM - 	Supported Products : 
1/12/2016 9:52:08 AM - 		Microsoft.VisualStudio.Pro
1/12/2016 9:52:08 AM - 			Version : [11.0,12.0)
1/12/2016 9:52:08 AM - 
1/12/2016 9:52:08 AM - 	References      : 
1/12/2016 9:52:08 AM - 		-------------------------------------------------------
1/12/2016 9:52:08 AM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
1/12/2016 9:52:08 AM - 		Name         : Visual Studio MPF 11.0
1/12/2016 9:52:08 AM - 		Version      : [11.0]
1/12/2016 9:52:08 AM - 		MoreInfoURL  : 
1/12/2016 9:52:08 AM - 		Nested       : No
1/12/2016 9:52:08 AM - 
1/12/2016 9:52:08 AM - 
1/12/2016 9:52:08 AM - Searching for applicable products...
1/12/2016 9:52:08 AM - Found installed product - Microsoft Visual Studio 2010 Ultimate
1/12/2016 9:52:08 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
1/12/2016 9:52:08 AM - Found installed product - Microsoft Visual Studio Premium 2013
1/12/2016 9:52:08 AM - Found installed product - Microsoft Visual Studio Professional 2013
1/12/2016 9:52:08 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/12/2016 9:52:08 AM - Found installed product - Global Location
1/12/2016 9:52:08 AM - Found installed product - ssms
1/12/2016 9:52:08 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by mirik123** [comment]
It happens because I compiled it on VisualStudio 2012.

In order to be run on VS 2013/2015 is has to be compiled by relevant VS.

**Comment by ivanov-georgi** [comment]
I was able to compile the extension in Visual Studio 2015, however I faced the following issues:
- most of the Microsoft.TeamFoundation* and Microsoft.VisualStudio.TeamFoundation* references were not resolved
- I had to install some packages from NuGet. here is packages.config:

>   <package id="Microsoft.AspNet.WebApi.Client" version="5.2.2" targetFramework="net45" />
>   <package id="Microsoft.AspNet.WebApi.Core" version="5.2.2" targetFramework="net45" />
>   <package id="Microsoft.Data.ConnectionUI" version="14.1.24720" targetFramework="net45" />
>   <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="2.16.204221202" targetFramework="net45" />
>   <package id="Microsoft.Office.Interop.Word" version="12.0.0" targetFramework="net45" />
>   <package id="Microsoft.TeamFoundation.Build.All" version="12.0.30723.1" targetFramework="net45" />
>   <package id="Microsoft.TeamFoundation.VersionControl.All" version="12.0.30723.2" targetFramework="net45" />
>   <package id="Microsoft.TeamFoundation.WorkItemTracking.All" version="12.0.30723.2" targetFramework="net45" />
>   <package id="Microsoft.TeamFoundationServer.Client" version="14.89.0" targetFramework="net45" />
>   <package id="Microsoft.TeamFoundationServer.ExtendedClient" version="14.89.0" targetFramework="net45" />
>   <package id="Microsoft.VisualStudio.Data" version="14.1.24720" targetFramework="net45" />
>   <package id="Microsoft.VisualStudio.OLE.Interop" version="7.10.6070" targetFramework="net45" />
>   <package id="Microsoft.VisualStudio.Services.Client" version="14.89.0" targetFramework="net45" />
>   <package id="Microsoft.VisualStudio.Services.InteractiveClient" version="14.89.0" targetFramework="net45" />
>   <package id="Microsoft.VisualStudio.Shell.Interop" version="7.10.6071" targetFramework="net45" />
>   <package id="Microsoft.VisualStudio.TextManager.Interop" version="7.10.6070" targetFramework="net45" />
>   <package id="Microsoft.WindowsAzure.ConfigurationManager" version="1.7.0.0" targetFramework="net45" />
>   <package id="Newtonsoft.Json" version="6.0.5" targetFramework="net45" />
>   <package id="System.IdentityModel.Tokens.Jwt" version="4.0.0" targetFramework="net45" />
>   <package id="WindowsAzure.ServiceBus" version="2.5.1.0" targetFramework="net45" />
> 
- I have to add a reference path in Project Properties -> Reference Paths to C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\ in my case. 

Even the plugin is compiled, it still shows the same error when installing it.

**Comment by msk266** [comment]
You'll have to edit the vsixmanifest, it's currently configured to only allow installations on Visual Studio 2012 Pro.
Install Targets specifically defines Version Range as [11.0, 12.0), it's probably easiest if you set it to [11.0,].
You can find more info about this [here](https://blogs.msdn.microsoft.com/visualstudio/2013/08/08/update-for-extension-authors-vsix-manifest-version-range-attribute/).

**Comment by thesonofman0** [comment]
Updated manifest for 2015- if you haven't figured it out on your own yet.

<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    <Identity Id="16bf0a1d-6239-485f-ac25-6fcd37d514c7" Version="2.1.0" Language="en-US" Publisher="Mark Babayev" />
    <DisplayName>TFS Productivity Tools</DisplayName>
    <Description xml:space="preserve">The TFS Productivity Tools project was designed to provide TFS administrators with helper extensions for Source Control or Work Item Tracking tasks.</Description>
    <MoreInfo>https://github.com/mirik123/tfsprod</MoreInfo>
    <License>Resources\The MIT License (MIT).txt</License>
    <Icon>Resources\gnome-globe.png</Icon>
    <PreviewImage>Resources\ExtendedMerge.png</PreviewImage>
    <Tags>TFS,WorkItems,SourceControl</Tags>
  </Metadata>
  <Installation InstalledByMsi="false">
    <InstallationTarget Id="Microsoft.VisualStudio.Ultimate" Version="[14.0]" />
    <InstallationTarget Version="[14.0]" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[14.0]" Id="Microsoft.VisualStudio.Premium" />
    <InstallationTarget Version="[14.0]" Id="Microsoft.VisualStudio.Community" />
  </Installation>
  <Dependencies>
    <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="4.5" />
    <Dependency Id="Microsoft.VisualStudio.MPF.14.0" DisplayName="Visual Studio MPF 14.0" Version="14.0" />
  </Dependencies>
  <Assets></Assets>
</PackageManifest>

**Comment by thesonofman0** [comment]
Here's an updated manifest for 2015- if you haven't figured it out on your own yet.

`<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    <Identity Id="16bf0a1d-6239-485f-ac25-6fcd37d514c7" Version="2.1.0" Language="en-US" Publisher="Mark Babayev" />
    <DisplayName>TFS Productivity Tools</DisplayName>
    <Description xml:space="preserve">The TFS Productivity Tools project was designed to provide TFS administrators with helper extensions for Source Control or Work Item Tracking tasks.</Description>
    <MoreInfo>https://github.com/mirik123/tfsprod</MoreInfo>
    <License>Resources\The MIT License (MIT).txt</License>
    <Icon>Resources\gnome-globe.png</Icon>
    <PreviewImage>Resources\ExtendedMerge.png</PreviewImage>
    <Tags>TFS,WorkItems,SourceControl</Tags>
  </Metadata>
  <Installation InstalledByMsi="false">
    <InstallationTarget Id="Microsoft.VisualStudio.Ultimate" Version="[14.0]" />
    <InstallationTarget Version="[14.0]" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[14.0]" Id="Microsoft.VisualStudio.Premium" />
    <InstallationTarget Version="[14.0]" Id="Microsoft.VisualStudio.Community" />
  </Installation>
  <Dependencies>
    <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="4.5" />
    <Dependency Id="Microsoft.VisualStudio.MPF.14.0" DisplayName="Visual Studio MPF 14.0" Version="14.0" />
  </Dependencies>
  <Assets></Assets>
</PackageManifest>`

**Comment by mirik123** [comment]
Updated latest release.

**Comment by mirik123** [comment]
Varnk hi.

Please see the new version of this package. 

It should allow installation on version 2012-2015.

If you will not be able to run tfsprod on VS2013 try to install VS2012+SKD in parallel to VS2013, it uses DLLs from VS2012 home directory.
