### ISSUE TITLE
Text under icons of Extended Merge is not readable

### ISSUE THREAD

**Issue by Styxion** [mirik123/tfsprod#2]
Hello, 
text under icons on the toolbar "Merge Changesets" is not readable because the list covers it (See screenshot). 

Also, the register of the merge-Tab has not text.

![tfs merge screenshot](https://cloud.githubusercontent.com/assets/18004546/13948394/03eacc8e-f020-11e5-9cd4-308d56b61461.png)

**Comment by mirik123** [comment]
Updated latest release
